aws.access.key=56af4f3898f94ffd20262afaf04a7b2a
aws.secret.access.key=vcUlVfB9zzhTFEh9AiBe5a8Gyh9F0ZJLqS1kdpfj
aws.s3.region=US
aws.s3.path.save=

spring.servlet.multipart.max-file-size=100000MB
spring.servlet.multipart.max-request-size=100000MB

minio.url=http://172.20.5.149:9000
minio.access.name=opA2RVv6X6OHUtwI1MhS
minio.access.secret=3WaX2N4WBhZfnlQkqT7JBMGwVgDgH7K1S0SZLORk
minio.bucket.name=backup42

