aws.access.key.first=
aws.secret.access.key.first=
aws.access.key.second=
aws.secret.access.key.second=
aws.s3.region=US

spring.servlet.multipart.max-file-size=100000MB
spring.servlet.multipart.max-request-size=100000MB



