aws.access.key.first=U4sdzQX1Ue4xYb5eoS4b
aws.secret.access.key.first=XyzgzLA5Rgkqv5Gg8m8ZkVMsK9u8bpQOkzcSEXdC
aws.access.key.second=40f2ddf8224c0968219a74742b4c9879
aws.secret.access.key.second=4wPyVi7S9qDNhbEmpXf2wMAT3rHHPT53eIjhxGAw
aws.s3.region=US

spring.servlet.multipart.max-file-size=100000MB
spring.servlet.multipart.max-request-size=100000MB



